#!/bin/bash
./doinstall.tcl -nox /tools/tkcvs/tkcvs_8_2
fuckrab=`find $1 -name $2`

for arg in $rab
do
    echo "deleting $arg ..."
    \rm -rf $arg
done 
print_help () {
	echo "NAME"
	echo "       create_project - create specified project and set environment variables accordingly"
	echo "SYNOPSIS"
    echo "       create_project project_name serial_name [--help] [--verbose]"
    exit 1
}

parse_comand () {
    arg_num=0
    for arg_cnt in $(seq 1 $#)
	do
		eval arg=\${$arg_cnt}

		case $arg in
        --help|-h|-\?) 
			arg_help=$arg_cnt
			print_help
            ;;
		--verbose|-v) 

