#!/usr/bin/tclsh

proc makedir { pathname } {
  if {[file isdirectory $pathname]} {
    return $pathname     
  } elseif {[file exists $pathname]} {
    puts "\[ERROR makedir\]: $pathname is not a directory and already exists."
    exit 0    
  } else {    
    makedir [file dirname $pathname]
	exec mkdir $pathname
    return $pathname
  }
}

makedir $argv
